"""
DocuMind AI — ChromaDB Vector Store
====================================
WHY CHROMADB?
    We need to store our embeddings and quickly search them using Cosine Similarity
    or L2 distance. ChromaDB is an excellent open-source, local-first vector DB
    that requires no external infrastructure (unlike Pinecone or Qdrant).
    It persists to disk and is perfect for a production MVP.

HOW THIS WORKS:
    We initialize the ChromaDB client pointing to our local persistence directory.
    When we insert chunks, we pass:
    1. The ID (chunk_id)
    2. The Text (the raw string)
    3. The Metadata (Heading, Page Number, etc.)
    4. The Embedding (The float vector)
"""

import chromadb
from loguru import logger
from typing import List, Dict, Any

from backend.config.settings import settings
from backend.embeddings.chunker import DocumentChunk

class VectorStore:
    """Wrapper for ChromaDB operations."""
    
    def __init__(self):
        logger.info(f"Connecting to ChromaDB at {settings.chromadb_path}")
        try:
            # PersistentClient saves data to disk so it survives server restarts
            self.client = chromadb.PersistentClient(path=str(settings.chromadb_path))
            self.collection = self._get_or_create_collection()
            logger.info(f"ChromaDB connected. Collection: {settings.chroma_collection_name}")
        except Exception as e:
            logger.error(f"Failed to initialize ChromaDB: {e}")
            raise RuntimeError(f"Vector Database failed to initialize: {e}")

    def _get_or_create_collection(self):
        # Using cosine similarity as the distance metric (standard for text embeddings).
        return self.client.get_or_create_collection(
            name=settings.chroma_collection_name,
            metadata={
                "hnsw:space": "cosine",
                "embedding_model": settings.embedding_model,
            },
        )

    def _reset_collection(self) -> None:
        """
        Recreate the active collection after an embedding-model dimension change.

        Chroma collections have a fixed vector dimensionality once the first
        embedding is inserted. If the configured embedding model changes, old
        vectors are incompatible and the local collection must be rebuilt.
        """
        logger.warning(
            "Recreating ChromaDB collection '{}' for embedding model '{}'.",
            settings.chroma_collection_name,
            settings.embedding_model,
        )
        try:
            self.client.delete_collection(settings.chroma_collection_name)
        except Exception as exc:
            logger.debug(f"Collection delete skipped or failed: {exc}")
        self.collection = self._get_or_create_collection()

    @staticmethod
    def _is_dimension_mismatch_error(exc: Exception) -> bool:
        message = str(exc).lower()
        return "dimension" in message and "dimensionality" in message

    def insert_chunks(self, chunks: List[DocumentChunk], embeddings: List[List[float]]) -> None:
        """
        Inserts document chunks and their corresponding embeddings into ChromaDB.
        """
        if not chunks or not embeddings:
            return
            
        if len(chunks) != len(embeddings):
            raise ValueError(f"Length mismatch: {len(chunks)} chunks vs {len(embeddings)} embeddings")

        ids = [chunk.chunk_id for chunk in chunks]
        documents = [chunk.text for chunk in chunks]
        metadatas = [chunk.metadata for chunk in chunks]
        
        logger.debug(f"Inserting {len(ids)} chunks into ChromaDB...")
        
        def add_chunks() -> None:
            self.collection.add(
                ids=ids,
                embeddings=embeddings,
                documents=documents,
                metadatas=metadatas
            )

        try:
            # Add to ChromaDB. We explicitly pass embeddings because they are
            # generated by our configured Ollama embedding model.
            add_chunks()
            logger.info(f"Successfully inserted {len(ids)} chunks into vector store.")
        except Exception as e:
            if self._is_dimension_mismatch_error(e):
                logger.warning(f"ChromaDB embedding dimension mismatch detected: {e}")
                self._reset_collection()
                try:
                    add_chunks()
                    logger.info(
                        f"Successfully inserted {len(ids)} chunks after recreating vector store."
                    )
                    return
                except Exception as retry_error:
                    logger.error(f"Failed to insert chunks after collection reset: {retry_error}")
                    raise RuntimeError(f"Vector Database insertion failed: {retry_error}")

            logger.error(f"Failed to insert chunks into ChromaDB: {e}")
            raise RuntimeError(f"Vector Database insertion failed: {e}")

    def search(self, query_embedding: List[float], n_results: int = settings.rag_top_k) -> Dict[str, Any]:
        """
        Performs a semantic search to find the most relevant chunks.
        """
        try:
            results = self.collection.query(
                query_embeddings=[query_embedding],
                n_results=n_results,
                include=["documents", "metadatas", "distances"]
            )
            return results
        except Exception as e:
            logger.error(f"Failed to search ChromaDB: {e}")
            raise RuntimeError(f"Semantic search failed: {e}")

# Singleton instance
vector_store = None

def get_vector_store() -> VectorStore:
    global vector_store
    if vector_store is None:
        vector_store = VectorStore()
    return vector_store
