"""
DocuMind AI — Local LLM Client (Ollama)
=========================================
WHY OLLAMA?
    For a production MVP focusing on privacy (Enterprise use-cases), we cannot send 
    sensitive PDFs to OpenAI. Ollama runs Llama-3 / Mistral locally.

HOW IT WORKS:
    This is an asynchronous HTTP client wrapping the Ollama REST API.
    We use `httpx` instead of `requests` because FastAPI is async. If we used
    `requests`, the entire server would freeze while waiting 5 seconds for the LLM.
"""

import httpx
from loguru import logger
from typing import List

from backend.config.settings import settings
from backend.api.schemas.chat import ChatMessage

class OllamaClient:
    """Async client for local Ollama API."""

    def __init__(self):
        self.base_url = settings.ollama_base_url
        self.model = settings.ollama_model
        # LLM generation can take a long time, so we set a high timeout.
        self.timeout = httpx.Timeout(120.0)

    async def generate_chat(self, system_prompt: str, user_prompt: str) -> str:
        """
        Calls the Ollama /api/chat endpoint.
        """
        url = f"{self.base_url}/api/chat"
        
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "stream": False,
            "options": {
                "temperature": 0.1,
                "num_gpu": settings.ollama_num_gpu
            }
        }
        
        logger.debug(f"Calling Ollama model {self.model}...")
        
        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(url, json=payload)
                response.raise_for_status()
                
                data = response.json()
                return data["message"]["content"]
                
        except httpx.RequestError as e:
            logger.error(f"Failed to connect to Ollama at {self.base_url}: {e}")
            raise RuntimeError(f"LLM Engine unreachable. Is Ollama running? Error: {e}")
        except Exception as e:
            logger.error(f"Ollama generation failed: {e}")
            raise RuntimeError(f"LLM generation failed: {e}")

    async def generate_chat_stream(self, system_prompt: str, user_prompt: str):
        """
        Yields text chunks as they are generated by the model.
        """
        url = f"{self.base_url}/api/chat"
        
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "stream": True,
            "options": {
                "temperature": 0.1,
                "num_gpu": settings.ollama_num_gpu
            }
        }
        
        try:
            import json
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                async with client.stream("POST", url, json=payload) as response:
                    response.raise_for_status()
                    async for line in response.aiter_lines():
                        if not line:
                            continue
                        data = json.loads(line)
                        if "message" in data and "content" in data["message"]:
                            yield data["message"]["content"]
                        if data.get("done"):
                            break
        except Exception as e:
            logger.error(f"Ollama streaming failed: {e}")
            yield f"\n[Error: Stream interrupted: {e}]"

# Singleton
ollama_client = None

def get_ollama_client() -> OllamaClient:
    global ollama_client
    if ollama_client is None:
        ollama_client = OllamaClient()
    return ollama_client
